In [1]:
import numpy as np

In [5]:
arr = np.full((3, 3), True)
print("arr:\n", arr)

arr_ID = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_ID.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("arr_2D sau khi đổi cột:\n", arr_2D)

arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("arr_2D sau khi đổi dòng:\n", arr_2D)

arr_2D = np.flip(arr_2D, axis=0)
print("arr_2D sau khi đảo ngược dòng:\n", arr_2D)

arr_2D = np.flip(arr_2D, axis=1)
print("arr_2D sau khi đảo ngược cột:\n", arr_2D)

arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
print("Có giá trị NaN trong arr_2D_null không?", np.isnan(arr_2D_null).any())

arr_2D_null[np.isnan(arr_2D_null)] = 0
print("arr_2D_null sau khi thay thế NaN:\n", arr_2D_null)

arr:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
arr_2D sau khi đổi cột:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
arr_2D sau khi đổi dòng:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]
arr_2D sau khi đảo ngược dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]
arr_2D sau khi đảo ngược cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]
Có giá trị NaN trong arr_2D_null không? True
arr_2D_null sau khi thay thế NaN:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
